### ISSUE TITLE
Multi-threaded version doesn't work in Electron

### ISSUE THREAD

**Issue by ZeronoFreya** [niutech/jxl.js#12]
## Error Info:
```
node:internal/worker:187 Uncaught (in promise) Error: The V8 platform used by this instance of Node does not support creating Workers
    at new Worker (node:internal/worker:187:21)
    at Object.allocateUnusedWorker (jxl_decoder_simd.min.js:1:15239)
    at Object.initMainThreadBlock (jxl_decoder_simd.min.js:1:10603)
    at jxl_decoder_simd.min.js:1:25077
    at process (jxl.js:155:20)
    at jxl.js:72:33
```

electron-v23.2.0-win32-x64

Is there any solution?

**Comment by niutech** [comment]
Sorry, Electron is not supported. Maybe use Tauri instead.
